require("nate.remap")
require("nate.set")
require("nate.lualine")
require("nate.oil")
require("nate.filetree")
require("nate.obsidian")
require("nate.qalc")
require("nate.luasnip")
require("nate.cmp")
-- vim.cmd("!afplay ~/.config/nvim/ring.mp3 & ")
